### PR TITLE
Escape rollbar JS

### PR DESCRIPTION
**Pull request by brianswko**
Prevents the `\n` characters in the `rollbar.js` from being interpreted as newlines within ruby code

### CODE REVIEW

**Comment by jdoconnor** [comment]
if that works, +1

**Comment by jdoconnor** [comment]
also, this is NOT for master
its for 1.x branch

**Comment by jdoconnor** [comment]
master is rails 4.

**Comment by brianswko** [comment]
Closing, opening https://github.com/lumoslabs/smoke_detector/pull/26 to merge into `1.x`

**Pull request closed without merging**
